apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gitops
  template:
    metadata:
      labels:
        app: nginx-gitops
    spec:
      containers:
      - name: nginx
        image: adbonino/nginx-site:d37b27c83247c921345fb3ef898fd0d6ea7d5f4f
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /workdir
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: nginx-html-pvc  
